project '/Users/benpu/Desktop/Codepath/Flix/flix/flix/Flix.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Flix' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Flix

end
